name: YOLO Achievement

on:
  workflow_dispatch:

jobs:
  run-yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say hi
        run: echo "YOLO Achievement Unlocked!"
